name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot app with Gradle

        run: |
          gradle wrapper
          ./gradlew clean build

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/pibbletv/pibbletv-user-service:latest  .

      - name: Test Docker image
        run: |
          docker run --rm -d --name user-service -p 8081:8081 ghcr.io/pibbletv/pibbletv-user-service:latest
          docker stop user-service


